apiVersion: v1
kind: ServiceAccount
metadata:
  name: hrs-gateway-sa
  namespace: uat
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hrs-maintenance-service-sa
  namespace: uat
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hrs-inventory-service-sa
  namespace: uat
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hrs-order-service-sa
  namespace: uat
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hrs-payment-service-sa
  namespace: uat
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hrs-user-service-sa
  namespace: uat
automountServiceAccountToken: false
